version: '3'

services:
  fire-detection:
    build: .
    container_name: fire-detection
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - MODEL_PATH=/app/models/fire_best.pt
